# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital Learning Competency Framework
organisation: Mark Berthelemy
url: https://digitallearningcompetencies.info
orgurl: https://mark.berthelemy.net
academy-url: https://www.wyversolutions.co.uk/academy
email: mark@berthelemy.net
description: Key skills for digital learning professionals working in corporate learning and development or higher education
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://mark.berthelemy.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
alert: This is an ALPHA version, designed to elicit feedback. It should not be used in any production service.

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed

collections:
    digital-learning-competencies:
        output: true

defaults:
  - scope:
      path: ""
      type: "digital-learning-competencies"
    values:
      layout: "competency"
      permalink: /competencies/:title

collections_dir: _collections

include: ['_pages']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

levels:
    level1:
        ID: Level 1
        name: Foundation
    level2:
        ID: Level 2
        name: Practitioner
    level3:
        ID: Level 3
        name: Advanced
